### ISSUE TITLE
Suggestions for implementation

### ISSUE THREAD

**Issue by lynnanthonissen** [emanjavacas/cleebo#1]
Below are a few suggestions for implementation, which I wrote down while doing some queries a couple of weeks ago. The first two in particular would be very useful for my case studies.
1.  Doing queries based on previously created tags, e.g. [cxn=“ppp”] or [pos=“prp”]. Currently, this doesn’t seem possible – I get a runtime error: property pos not found.
2.  Being able to mark hits as irrelevant and disregard them in future queries
3.  Possibility to do queries within a query
4.  A function to save queries
5.  The snippet function works fine, but it opens in an extra window. Would it be possible to integrate the snippet into the active screen so that you can add tags while looking at the larger text without having to go back and forth all the time? That could save us a lot of time in the long run.
6.  A function to move through pages more quickly (Say you have 10,000 hits, which you sort alphabetically on the first word. Since 125 hits per page is the maximum number you have to click through a lot of pages to get to the end or even to the page where you did your last annotations)
7.  SORT BY: currently the options are MATCH, LEFT-CONTEXT, RIGHT-CONTEXT >> It would be useful to be able to sort on the second, third, … token of the query (as the first token is not always informative). This way I could sort on VERB and annotate all instances of a particular verb (or construction), e.g. _be sent for_, at once. Obviously if you allow for words between the auxiliary and the past participle, the second token will not always be the V, but even then the function would still be useful for the majority of examples. (Also, in my case for marking a number of examples as irrelevant, e.g. _be fond of_)
8.  Selecting hits using keys (CRTL and arrows)
9.  Similarly, being able to use the Enter-key instead of the “submit”-button (see image)

![image](https://cloud.githubusercontent.com/assets/20626036/17084394/9c0c017e-51bc-11e6-9f28-93ad1ffb4b16.png)

**Comment by Meriadocus** [comment]
1. The possibility to open (in the annotation panel) all annotation cells at once (right now you have to click each example separately).

**Comment by emanjavacas** [comment]
There are quite a lot of different issues/suggestions here, and many of them have been solved in the meantime or are not easy to implement in the short term. I will open those that need be worked on in new issues. For the future, please try to single out different issues/suggestion as such and open a new GitHub issue when needed.
