### ISSUE TITLE
[BUG] span annotation applied to wrong span

### ISSUE THREAD

**Issue by qwallath** [emanjavacas/cleebo#14]
I encountered a bug when trying to apply a span annotation in the following situation:

- the left side of the window showed the right edge of a previous set of annotations — the two hits are near each other in the text

I tried to apply the annotation to a particular span (see fig. 1)

However, after annotating, the annotation was applied to a span a bit more to the left, overlapping with part of the earlier annotations. Tried it twice, same result (fig. 2).

fig. 1: [https://www.dropbox.com/s/g2spuo5worr2acc/growbug1.PNG?dl=0](https://www.dropbox.com/s/g2spuo5worr2acc/growbug1.PNG?dl=0)
fig. 2: [https://www.dropbox.com/s/b64b69r27385uun/growbug2.PNG?dl=0](https://www.dropbox.com/s/b64b69r27385uun/growbug2.PNG?dl=0)

**Comment by emanjavacas** [comment]
I've checked a bit and it seems to be a problem with the display and not with the storage of annotations. I will try to replicate it independently and see what's going on.

**Comment by emanjavacas** [comment]
[UPDATE] The issue has to do with https://github.com/emanjavacas/cosycat/blob/master/src/cljs/cosycat/annotation/components/annotation_row.cljs#L56

In case the one annotation spans to the right  of the visible hit, colspans are being miscalculated.

For the moment, you can check this by ensuring a large enough window.
I will fix this and include it in the next release.

**Comment by emanjavacas** [comment]
59a56c8 to 5b837ce should have fixed this. As an extra, now partial spans are shown too in case they overflow the current window size (both by the left and by the right side)
