### ISSUE TITLE
Hit scroller in annotation pane.

### ISSUE THREAD

**Issue by WillStanding** [emanjavacas/cleebo#16]
I'm not sure if this is a bug or a work in progress but it is associated with what we discussed the other day regarding the scrolling arrows on the hits in the annotation window. We talked about changing the method of adding words to the annotation window of the hit to a scrolling system with the hit remaining tied to one end.

 I see that the scrolling seems to be active but it also seems to go no further than the hit reaching either end of the pane, cycling back round if more words are added. This makes it pretty much impossible to do annotation of a full phrase. 

 I'm not sure what the fix would be; if the scrolling is too time-consuming to add without encountering issues like this, the former system is perfectly usable and preferable to having the hit fixed in the frame.

**Comment by emanjavacas** [comment]
5df9fba should've fixed this now
