### ISSUE TITLE
Some filters don't work with some corpora

### ISSUE THREAD

**Issue by Meriadocus** [emanjavacas/cleebo#8]
Author filter, author ID with MBG-indexed. But works fine with MBG-notes-indexed. 
Also, date seems to work with some dates, but not with others (e.g. query "going" works with a filter 1681, but not with a filter 1651. What's going on???

**Comment by emanjavacas** [comment]
"Doesn't work", "work" is not really telling much. If you mean you are getting an error with code 32, this is the same issue I am already investigating and it depends on BlackLab, so there is not much left for me to do until I get a clear answer and a fix from them. See https://github.com/INL/BlackLab/issues/33

**Comment by Meriadocus** [comment]
Yes, that's what I mean. Apologies, I forgot it was a Blacklab issue. It puzzles me exceedingly though, especially because they still all work fine with notes-corpus. I explained the work-bit somewhat in my comment though, don't know how to be more precise. But never mind, lets hope we get a response from Blacklab soon.

---

Peter Petréhttps://www.uantwerpen.be/en/staff/peter-petre/
Research Professor
UAntwerpen / ERC
May the grammar bend your mind! https://www.uantwerpen.be/en/projects/mind-bending-grammars/
